dist: trusty
language: csharp
node_js: 8
dotnet: 2.0.0
mono: none
solution: ZulipCSharp.sln

cache:
  - test-server/node_modules

script:
  - ./tools/build-project
  - ./tools/run-tests

notifications:
  webhooks:
    - https://dotnet.zulipchat.com/api/v1/external/travis?stream=CI&topic=build-status&api_key=$TRAVIS_BOT_KEY
