dist: trusty
language: csharp
node_js: 8
dotnet: 2.0.0
mono: none
solution: ZulipCSharp.sln

cache: 
  - TestServer/node_modules

install:
  - ./build-project

script:
  - ./run-tests

notifications:
  webhooks:
    - https://dotnet.zulipchat.com/api/v1/external/travis?stream=CI&topic=build-status&api_key=k1gIKIdX2Bp7VP1v2VhTclkAv4vTB9rx
